### PR TITLE
Adding connection info test widget

### PR DESCRIPTION
**Pull request by leewardbound**
Please help me test this for various failure scenarios, and in various browsers --

+ Tested in Chromium on Linux, seems to work in Firefox too

+ The idea is to simplify debugging `ion` issues down to "How many green checks do you see?"

I'm creating this PR now so I can attach UI screenshots, please don't merge until it's been thoroughly tested.

Successful Connection
===
image

Debug Tooltips
===
image

SFU Offline (Biz OK but can't join a room)
===
image

### CODE REVIEW

**Comment by tarrencev** [comment]
This looks great!

**Comment by cryptix** [comment]
I tested this a bunch on macOS, iOS and Android and as far as I can tell it works as expected. The only _mildly_ confusing thing is if you deny access to the cameras (or there are none) there is no orange warning sign or red X but no sign at all. Still awesome work @leewardbound!


# (linux) desktop (firefox) without a camera available (no checkmarks or warning sign)
ionapp-nocam

# android perm dialog
ionapp-web-test-android1

# android (chrome) perm dialog
ionapp-web-test-android2

# android (chrome) perms accepted
ionapp-web-test-android3

# iOS13 stays pending
ionapp-web-test-ios1

(I guess this is expected due to https://github.com/pion/ion-sfu/issues/23)

**Comment by jbrady42** [comment]
This is really cool. Maybe put behind a "Test Connection" button so its not running every time you open the page.

**Comment by cryptix** [comment]
@jbrady42: I could be wrong but it’s my understanding that this data is just gathered and displayed from the _normal_ connection establishment, making failures easily visible. Meaning it’s not a separate test run.

**Comment by leewardbound** [comment]
@cryptix - That's not correct actually! To gather the connection availability, we join a secret room (`Lobby-{math.random()}`) to debug the connection state.

I think I agree with @jbrady42 that this best belongs behind a button; the goal is to reduce support requests that don't have good debug information, by providing a big red X that explains why user's `ion` connection isn't functional -- As long as we make the button pronounced on the `Join` screen (and not hidden in a menu), having a button that says `[Test Connection]` should suffice here.

I'll try to get to this a bit later in the week, I'm prioritizing `e2e-tests` higher right now

**Comment by Sean-Der** [comment]
Amazing work @leewardbound. This is going to have a massive impact on debugging issues.

Would be possible to join `Lobby-{math.random()}` with just a DataChannel at first? Then enable webcam when user accepts. This would help us debug network connectivity issues, and we don't have to worry about user interaction on startup!

You also don't need to re-negotations or anything fancy! You could create a whole new PeerConnection, and only do `getUserMedia` when needed.

Happy to help with the dev work and answer any questions :)

**Comment by leewardbound** [comment]
@Sean-Der -- I looked into this, but I think currently the PeerConnection is only opened in `ion-sdk-js` when we `publish(SDP)` -- I assumed this meant we needed camera access, is there some way we can craft an SDP for just a data channel? If you could help me understand that portion, so we can continue using the `publish()` from `ion-sdk-js` I'd be glad to upgrade to that.

In that case, if we are using only a `DataChannel` and not requesting camera access, should we:
1) still hide this behind a `Test Connection` button ?
2) don't hide this behind a button because we don't ask for camera access anymore, show visual indicator on page load
3) both: automatically connect to the DataChannel, and the `TestConnection` button triggers a full camera request (with a Magic Mirror?)

@jbrady42  thoughts?

**Comment by leewardbound** [comment]
@jbrady42 Added as requested :) 
image

**Pull request merged**
